---
name: Updater Check
on:
  workflow_dispatch: {}
  schedule:
    # Run weekly
    - cron: '42 5 * * 1'

jobs:
  test_schedule:
    name: Periodic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: ./go.mod
      - run: go test ./test/periodic -enable
